[package]
name = "fuse-mt"
version = "0.1.0"
authors = ["William R. Fraser <wfraser@codewise.org>"]

[dependencies]
daemonize = "0.2"
fuse = "0.2"
libc = "0.2"
log = "0.3"
syslog = "3.1"
threadpool = "1.0"
time = "0.1"
